// <auto-generated />
using System;
using JulianaSosaGestorPacientesWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JulianaSosaGestorPacientesWeb.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240602210407_JSDB")]
    partial class JSDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JulianaSosaGestorPacientesWeb.Models.JSCategoria", b =>
                {
                    b.Property<int>("JSCategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JSCategoriaID"));

                    b.Property<DateTime>("JSFechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("JSGravedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JSPacienteID")
                        .HasColumnType("int");

                    b.HasKey("JSCategoriaID");

                    b.HasIndex("JSPacienteID");

                    b.ToTable("JSCategoria");
                });

            modelBuilder.Entity("JulianaSosaGestorPacientesWeb.Models.JSPaciente", b =>
                {
                    b.Property<int>("JSPacienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JSPacienteID"));

                    b.Property<string>("JSApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JSDNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JSEnfermedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JSNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JSPacienteID");

                    b.ToTable("JSPaciente");
                });

            modelBuilder.Entity("JulianaSosaGestorPacientesWeb.Models.JSCategoria", b =>
                {
                    b.HasOne("JulianaSosaGestorPacientesWeb.Models.JSPaciente", "JSPaciente")
                        .WithMany("JSCategoria")
                        .HasForeignKey("JSPacienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JSPaciente");
                });

            modelBuilder.Entity("JulianaSosaGestorPacientesWeb.Models.JSPaciente", b =>
                {
                    b.Navigation("JSCategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
